// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * Provides the desired configuration for a Web Application Firewall that can be referenced within WebFirewallPolicies and applied to incoming requests.
 */
export class WebApplicationFirewall extends pulumi.CustomResource {
    /**
     * Get an existing WebApplicationFirewall resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): WebApplicationFirewall {
        return new WebApplicationFirewall(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:gateway.getambassador.io/v1alpha1:WebApplicationFirewall';

    /**
     * Returns true if the given object is an instance of WebApplicationFirewall.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WebApplicationFirewall {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WebApplicationFirewall.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"gateway.getambassador.io/v1alpha1" | undefined>;
    public readonly kind!: pulumi.Output<"WebApplicationFirewall" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * Defines the desired user configuration for the WebApplicationFirewall.
     */
    public readonly spec!: pulumi.Output<outputs.gateway.v1alpha1.WebApplicationFirewallSpec>;
    /**
     * Provides a list of conditions that describe the current state of the WebApplicationFirewall for fast feedback on whether the resource is configured correctly or not.
     */
    public readonly status!: pulumi.Output<outputs.gateway.v1alpha1.WebApplicationFirewallStatus | undefined>;

    /**
     * Create a WebApplicationFirewall resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: WebApplicationFirewallArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "gateway.getambassador.io/v1alpha1";
            resourceInputs["kind"] = "WebApplicationFirewall";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(WebApplicationFirewall.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a WebApplicationFirewall resource.
 */
export interface WebApplicationFirewallArgs {
    apiVersion?: pulumi.Input<"gateway.getambassador.io/v1alpha1">;
    kind?: pulumi.Input<"WebApplicationFirewall">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * Defines the desired user configuration for the WebApplicationFirewall.
     */
    spec?: pulumi.Input<inputs.gateway.v1alpha1.WebApplicationFirewallSpecArgs>;
    /**
     * Provides a list of conditions that describe the current state of the WebApplicationFirewall for fast feedback on whether the resource is configured correctly or not.
     */
    status?: pulumi.Input<inputs.gateway.v1alpha1.WebApplicationFirewallStatusArgs>;
}
