// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * WebApplicationFirewallPolicy provides a way to apply Web Application Firewall configs against incoming requests for use cases such as configuring different WAF rules on a per-route basis.
 *  If no WebApplicationFirewall is provided then the request will be allowed through to the upstream service (pending execution of any Filters/Filterpolicies) without any additional WAF processing.
 */
export class WebApplicationFirewallPolicy extends pulumi.CustomResource {
    /**
     * Get an existing WebApplicationFirewallPolicy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): WebApplicationFirewallPolicy {
        return new WebApplicationFirewallPolicy(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:gateway.getambassador.io/v1alpha1:WebApplicationFirewallPolicy';

    /**
     * Returns true if the given object is an instance of WebApplicationFirewallPolicy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WebApplicationFirewallPolicy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WebApplicationFirewallPolicy.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"gateway.getambassador.io/v1alpha1" | undefined>;
    public readonly kind!: pulumi.Output<"WebApplicationFirewallPolicy" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta>;
    /**
     * Defines the desired user configuration for a WebApplicationFirewallPolicy that contains a set of rules that configure which WebApplicationFirewallPolicy to use for requests.
     */
    public readonly spec!: pulumi.Output<outputs.gateway.v1alpha1.WebApplicationFirewallPolicySpec>;
    /**
     * Provides a list of conditions that describe the current state of the WebApplicationFirewallPolicy for fast feedback on whether the resource is configured correctly or not.
     */
    public readonly status!: pulumi.Output<outputs.gateway.v1alpha1.WebApplicationFirewallPolicyStatus | undefined>;

    /**
     * Create a WebApplicationFirewallPolicy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: WebApplicationFirewallPolicyArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "gateway.getambassador.io/v1alpha1";
            resourceInputs["kind"] = "WebApplicationFirewallPolicy";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(WebApplicationFirewallPolicy.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a WebApplicationFirewallPolicy resource.
 */
export interface WebApplicationFirewallPolicyArgs {
    apiVersion?: pulumi.Input<"gateway.getambassador.io/v1alpha1">;
    kind?: pulumi.Input<"WebApplicationFirewallPolicy">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * Defines the desired user configuration for a WebApplicationFirewallPolicy that contains a set of rules that configure which WebApplicationFirewallPolicy to use for requests.
     */
    spec?: pulumi.Input<inputs.gateway.v1alpha1.WebApplicationFirewallPolicySpecArgs>;
    /**
     * Provides a list of conditions that describe the current state of the WebApplicationFirewallPolicy for fast feedback on whether the resource is configured correctly or not.
     */
    status?: pulumi.Input<inputs.gateway.v1alpha1.WebApplicationFirewallPolicyStatusArgs>;
}
